"""Create job applications and users tables

Revision ID: 86adf6e9e730
Revises: 6604b3dcd7b7
Create Date: 2026-09-02 11:41:14.959489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86adf6e9e730'
down_revision = '6604b3dcd7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    op.drop_table('users')
    # ### end Alembic commands ###
