"""Create job applications and users tables

Revision ID: 86adf6e9e730
Revises: 6604b3dcd7b7
Create Date: 2026-09-02 11:41:14.959489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86adf6e9e730'
down_revision = '6604b3dcd7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'PHONE_SCREEN', 'INTERVIEW', 'OFFER', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    op.drop_table('users')
    # ### end Alembic commands ###
