"""Create users and job applications tables

Revision ID: b7fa6b57a8b7
Revises: c176f524b540
Create Date: 2026-09-02 16:00:20.951151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fa6b57a8b7'
down_revision = 'c176f524b540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    op.drop_table('users')
    # ### end Alembic commands ###
