"""Add resume path to job applications

Revision ID: 7ebb6a0d2233
Revises: b7fa6b57a8b7
Create Date: 2026-09-03 11:11:16.681030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebb6a0d2233'
down_revision = 'b7fa6b57a8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
