"""Add interview scheduling fields

Revision ID: da10fc7a663e
Revises: 54c4bd8a942c
Create Date: 2026-09-07 17:36:51.597610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da10fc7a663e'
down_revision = '54c4bd8a942c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'job_applications',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP')
        )
    )
    op.add_column(
        'job_applications',
        sa.Column('interview_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'job_applications',
        sa.Column(
            'interview_reminder_sent_at',
            sa.DateTime(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'interview_reminder_sent_at')
    op.drop_column('job_applications', 'interview_at')
    op.drop_column('job_applications', 'updated_at')
    # ### end Alembic commands ###
